### PR TITLE
Maps_percents

### PR DESCRIPTION
**Pull request by DanyeleL**
Created Maps_percents

### CODE REVIEW

**Comment by DanyeleL** [comment]
Maps_percents pull request

**Review by lucrus73 — COMMENTED** [review]
Please look at [this issue](https://github.com/lucrus73/vacancyshop/issues/8). This patch is good in what it does, but it's incomplete.
In its current form is not very useful: you obtain the same results using [the corresponding jsfiddle code](https://jsfiddle.net/lucrus/s7taLowv/130/).
We basically need two more things:

1. save new accommodation data into the WP database
2. let the user choose the map to work on

**Comment by DanyeleL** [comment]
Add database in wordpress for Maps_percents and choose for map to work. IMPORTANT, Reload the plugin for write table in db in wordpress and delete the file in models/img or upload image of hotel and select it ( select and upload in Maps_percents, not in Media panel ).

**Comment by lucrus73** [comment]
Thanks for your effort, but we do not need nor want new tables in the database. Accommodations in VS are already stored in the wp_posts table as they are a custom post type managed by WordPress in its own tables.
[Here](https://codex.wordpress.org/Post_Types) you can find a generic overview of Custom Post Types (CPT for short).
VS already registers a CPT named Accommodation. You should create records into the database using the [wp_insert_post](https://developer.wordpress.org/reference/functions/wp_insert_post/) function or similar.

**Pull request closed without merging**
